POST http://127.0.0.1:8000/api/v1/auth/registro
Accept: application/json
Content-Type: application/json

{
    "name": "admin",
    "email": "pedro@mail.com",
    "password": "pedro54321",
    "c_password": "pedro54321"
}


### Login
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "pedro@mail.com",
    "password": "pedro54321"
}

### perfil
GET http://127.0.0.1:8000/api/v1/auth/perfil
Accept: application/json
Authorization: Bearer 41cm3DsvfNRcPoNrAUtachy99gu4Wp5eBfjGmsJw

### salir
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 41cm3DsvfNRcPoNrAUtachy99gu4Wp5eBfjGmsJw
